#4/grade inquiry
llocr/TEAM88 pull request #11
Opened 2024-05-03 03:29 UTC by gaeun7

## 📌 연관된 이슈

> Issue Number : #이슈번호

## PR 종류
해당 PR은 어떤 부분에 대한 변화인가요?

- [ ] 버그 수정 `FIX`(Hotfix)
- [ ] 코드 수정 `MODIFY`
- [ ] 기능 추가 `FEAT`
- [ ] 파일 이름 변경 `RENAME`
- [ ] 테스트 코드 추가 `TEST`
- [ ] 코드 스타일 변화 (formatting, local variables) `STYLE`
- [ ] 리팩토링 (no functional changes, no api changes) `REFACTOR`
- [ ] 빌드 관련 내용 추가 및 변화 `BUILD`
- [ ] 문서 내용 추가 및 변화`DOCS`
- [ ] 기타 변경 사항 추 `CHORE`
- [ ] Other... (적어주세요 : )

## 💻 작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해 주세요 (이미지 첨부 가능)

## 해당 PR이 다른 영역에 영향을 미치나요?
- [ ] Yes
- [ ] No

## 💬 리뷰 요구사항
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2024-05-03 04:31 UTC, llocr requested changes
아직 점수 등록 기능이 없어서 개발하는 데 쉽지 않으셨을 것 같아요!
그래도 HashMap으로 테스트 데이터를 넣으신 걸 보니 지금 있는 코드를 저희 팀 프로젝트 구조에 맞게 잘 번경하면 될 것 같습니다 😊 (테스트 데이터도 구조에 맞게 변경해 보시면 코드 작성하기가 수월하실 거에요!)

그리고 따로 클래스를 만들지 마시고 `App.java` 파일 내에서 메소드로 작업해주세요!!

헷갈리는 부분이 있으시다면... 저를 다시 찾아와 주시면 됩니다!

2024-05-03 04:31 UTC, llocr commented on src/StudentGradeSearch.java
> +        System.out.print("학생의 이름을 입력하세요: ");
저희는 수강생의 `studentId` 값으로 수강생 리스트의 key 값을 사용할 거여서, `수강생의 ID값`을 검색하는 것으로 바뀌어야 할 것 같아요!

2024-05-03 04:31 UTC, llocr commented on src/StudentGradeSearch.java
> +        HashMap<String, HashMap<String, HashMap<String, String>>> studentGrades = new HashMap<>();
이 코드는 테스트 용이겠죠..? 🥸
지금은 과목에 점수를 저장하는 기능이 만들어져 있지 않아서 이렇게 쓰신 것이라고 생각할게요..!

원래는 studentList의 key 값으로 저장된 value -> Student 객체를 가져오고
그 객체에서 scores Map `Map<Subject, Map<Integer, Score>>` 에서 key값인 Subject를 비교해서
맞는 Subject(사용자가 출력하고 싶은 Subject)에 저장된 `Map<Integer, Score>`를 출력해 주어야 해요!

`Map<Integer, Score>` 에서
Integer는 회차, Score는 점수 객체입니다

출력할 때는 회차(Map의 key)와 Score 객체 내부에 있는 grade 필드를 조회해 주어야 합니다!

구조가 이해되지 않으신다면 다시 물어봐 주세요!!

2024-05-03 04:31 UTC, llocr commented on src/StudentGradeSearch.java
>          if (studentGrades.containsKey(studentName)) {
여기도 studentList에서 studentId 값이 존재하는지 확인해야 합니다!

2024-05-03 04:31 UTC, llocr commented on src/StudentGradeSearch.java
> +        System.out.print("과목을 입력하세요 (객체지향언어, 자바, SQL): ");
이 부분은 학생이 수강하고 있는 과목들을 보여주고,
그 중에서 사용자가 선택하게 하는 것이 어떨까요? 😀

2024-05-03 04:31 UTC, llocr commented on src/StudentGradeSearch.java
> +            HashMap<String, HashMap<String, String>> sessions = studentGrades.get(studentName);
`studentList.get(studentId).get(scroes)` 로 받아야 할 것 같네요 :)

2024-05-03 04:31 UTC, llocr commented on src/model/Student.java
> +    private Map<Subject, Map<String, Score>> scores;
이 부분은 회차와 관련된 부분이라서 수정하시면 안 될 것 같아요! ㅎㅎ

2024-05-03 04:41 UTC, gaeun7 commented on src/StudentGradeSearch.java
> +        System.out.print("학생의 이름을 입력하세요: ");
그럼 입력을 이름이 아니라 수강생ID로 하는건가요?

2024-05-07 08:28 UTC, llocr reviewed
굿굿 너무 좋아요!
나중에 반환을 Grade로 고치기만 하면 될 것 같습니당 :)

2024-05-07 08:28 UTC, llocr commented on src/App.java
> +        System.out.print("과목 ID를 입력하세요: ");
학생이 수강하고 있는 과목 이름과 과목 ID를 보여주어도 좋을 것 같네요!!

2024-05-07 09:08 UTC, gaeun7 commented
![image](https://github.com/llocr/TEAM88/assets/162283154/78504267-0ca8-4f53-bf8f-123a23513b0a)

2024-05-07 09:13 UTC, llocr approved these changes
너무 수고하셨어요! merge 하겠습니다 :) 💗

2024-05-07 09:13 UTC, llocr commented on src/App.java
> +    System.out.println("학생 " + studentId + "의 과목 " + subjectId + "의 학점:");
나중에는 student 이름과 subject 이름이 같이 나오게 수정해봐도 좋을 것 같네요!

2024-05-07 09:13 UTC, merged