#5/update score , 점수 수정기능 추가
llocr/TEAM88 pull request #12
Opened 2024-05-03 07:49 UTC by seongchankim1

## 📌 연관된 이슈

> Issue Number : #5

## PR 종류
해당 PR은 어떤 부분에 대한 변화인가요?

- [ ] 버그 수정 `FIX`(Hotfix)
- [ ] 코드 수정 `MODIFY`
- [ V ] 기능 추가 `FEAT`
- [ ] 파일 이름 변경 `RENAME`
- [ ] 테스트 코드 추가 `TEST`
- [ ] 코드 스타일 변화 (formatting, local variables) `STYLE`
- [ ] 리팩토링 (no functional changes, no api changes) `REFACTOR`
- [ ] 빌드 관련 내용 추가 및 변화 `BUILD`
- [ ] 문서 내용 추가 및 변화`DOCS`
- [ ] 기타 변경 사항 추 `CHORE`
- [ ] Other... (적어주세요 : )

## 💻 작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해 주세요 (이미지 첨부 가능)

## 해당 PR이 다른 영역에 영향을 미치나요?
- [ ] Yes
- [ ] No

## 💬 리뷰 요구사항
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2024-05-03 08:36 UTC, llocr requested changes
성찬님 너무 수고하셨어요!
아직 점수 등록 기능이 없어서 조오금? 힘드셨을 것 같아요!

리뷰 남겨드린 내용 확인하시고, 수정할 부분 수정해 주시면 될 것 같습니다!
혹시 헷갈리시는 부분이 있거나 이해가 잘 되지 않으시다면 꼭 이야기해 주세요 🤗

2024-05-03 08:36 UTC, llocr commented on src/App.java
> +    private static HashMap<String, Student> studentList = new HashMap<>();
이 HashMap과 List는 `setInitData()` 메소드에서 초기화가 됩니다! 여기서 초기화 안 하셔도 될 것 같아요 :)

2024-05-03 08:36 UTC, llocr commented on src/App.java
> +    private static HashMap<String, HashMap<String, HashMap<String, String>>> studentGrades = new HashMap<>();
이 코드는,, 작업을 위해 작성하신 것이라고 생각하겠습니다!!
학생들의 점수는 student 객체에 있는 scores 필드에서 가져오셔야 합니다!!

scores의 구조는 <Subject, Map<Integer, Score>>로 되어있는데요

수정하려는 학생을 studentList에서 studentId를 이용해서 찾고 (사용자에게 studentId를 입력 받아야 합니다.
찾은 학생의 scores에 접근해서 수정할 과목을 고르게 합니다.
과목을 골랐다면, 점수를 수정할 회차를 선택해서 저장된 Score 객체를 가져와야 합니다!

저장된 score 객체를 가져오는 코드는 아래와 같습니다.
`Score score = studentList.get(studentId)).getScores().get(subjectList.get(0)).get(1);`
subjectList의 0번째 과목을 학생이 수강하고 있고, 그 과목의 1번째 회차 점수를 바꾸고 싶다고 한다고 가정해본 코드입니다.

조금,, 어지럽죠?

이제 우리가 꺼낸 score 객체의 점수를 수정해 주면 됩니다 `score.setScore(80); `

이제 값을 수정한 객체를 다시 student의 scores에 넣어줘야 합니다
`studentList.get(student.getStudentId()).getScores().get(subjectList.get(0)).put(1, score);`

학생의 아이디 값을 받고, 수정할 과목 / 회차 / 점수를 입력 받는 과정은 생략했습니다!

저는 중간중간 객체를 추출하지 않았는데, 만약 객체를 추출해서 정보를 변경하신다면 꼭꼭 다시 변경한 객체를 원래 자리에 put 해주셔야 합니다 :)

2024-05-03 08:36 UTC, llocr commented on src/App.java
> -        subjectList = List.of(
subjectList에 있는 객체들은 시작부터 등록되어 있어야 하는 것들이라서 삭제하시면 안 됩니당 🙅‍♀️

2024-05-03 08:36 UTC, llocr commented on src/App.java
> +                //case 2 만들어서 추가해주세요!
develop 브랜치 최신화 된 버전 pull 안 받으신 것 같아요!
pull 당겨 주세요..~~👍

2024-05-03 08:36 UTC, llocr commented on src/App.java
> +        String studentName = sc.next();
이름이 아닌 studentId를 받아 주셔야 합니다!

2024-05-03 08:36 UTC, llocr commented on src/App.java
> +        List<Score> scores = scoreMap.get(studentId);
점수가 정보가 없는 걸 확인하시려면, 무슨 과목을 선택할 건지 확인 후에

`studentList.get(studentId).getScores().get(subjectList.get(0)).isEmpty();`

이렇게 확인하셔야 할 겁니다!

2024-05-07 02:16 UTC, seongchankim1 commented on src/App.java
> +        String studentName = sc.next();
일부러 입력이 편하지 않을까 해서 이름을 받아서 그걸 ID로 바꾸는 메서드(findStudentIdByName)을 추가해봤었던거였는데 이 방법 말고 ID를 바로 받아서 하는거로 바꿀까용?

2024-05-07 02:25 UTC, llocr commented on src/App.java
> +        String studentName = sc.next();
동명이인이 있을 경우도 있어서요! 🥺

사용자 편의를 위한 거라면, 메뉴에
이름을 검색하면, 검색된 이름을 가진 ID 값을 보여 주는 메소드를 추가해보는 방식은 어떨까요?!

2024-05-07 10:53 UTC, llocr approved these changes
코드 확인했습니다! 수고하셨어요 👍

2024-05-07 10:53 UTC, llocr commented on src/model/Score.java
> +    public static HashMap<String, List<Score>> scoreMap = new HashMap<>();
삭제해주셔도 될 것 같습니당!

2024-05-07 10:53 UTC, llocr commented on src/App.java
> +    }
코드 분리해 주신 거 너무 좋네요! 아주 깔끔!! 👍👍

2024-05-07 11:02 UTC, merged